-- ---------------------------------------------------------------------------
-- An auditor covers places, not postcodes.
--
-- Three UK assumptions were baked into the schema, and one of them was fatal:
--
--   audit.postcode          CHECK against a UK postcode regex — a Dublin or
--                           Berlin address was rejected on insert. Not matched
--                           badly: refused outright.
--   audit.postcode_area     generated by slicing UK postcode syntax.
--   auditor_coverage        CHECK (postcode_area ~ '^[A-Z]{1,2}$').
--
-- Postcode areas are a UK implementation detail that had leaked all the way
-- into the interface — an auditor was being asked to translate "how far will I
-- travel" into geography they would have to look up. Three things are true in
-- every country instead: a point, a willingness to travel, and a place name.
--
-- ## What matching becomes
--
-- Still a join, which is the property the postcode-area design was chosen for:
--
--   auditor_coverage.place_id = audit.place_id
--
-- No distance arithmetic in the request path, no routing service, no parsing in
-- application code. The geometry runs ONCE, when an auditor saves their
-- coverage, to propose the list of places — and what we store is the list they
-- confirmed, not the circle that suggested it.
--
-- `max_travel_minutes` and `travel_mode` are recorded as the auditor gave them,
-- so real journey times can replace the straight-line estimate later without
-- asking anybody anything again.
--
-- ## What this migration does NOT do
--
-- `postcode_outward` stays, and the field app still displays it. It is a label,
-- not a matching key, and switching the apps to place names is a separate
-- change with its own tests. For a non-UK address it will be null — which is
-- why the display should move, and why it is written down here.
-- ---------------------------------------------------------------------------

create type public.travel_mode as enum ('public_transport', 'own_vehicle', 'either');

/**
 * Somewhere a person would name.
 *
 * Roughly a town, borough or district — the unit somebody says out loud when
 * asked where they work. In the UK that is close to a local authority district;
 * elsewhere it is whatever the equivalent administrative level is called.
 *
 * `region` disambiguates: there is a Richmond in London and a Richmond in North
 * Yorkshire, and an auditor picking between them needs to see which is which.
 *
 * Seeded per country from open data. A second country is rows in this table,
 * not a schema change — which is the entire point.
 */
create table public.place (
  id           uuid primary key default public.uuid_generate_v7(),
  country_code char(2) not null,
  name         text not null,
  region       text,
  latitude     double precision not null,
  longitude    double precision not null,
  created_at   timestamptz not null default now(),

  constraint place_name_not_empty check (length(trim(name)) > 0),
  constraint place_latitude_sane  check (latitude between -90 and 90),
  constraint place_longitude_sane check (longitude between -180 and 180)
);

-- One row per named place within a region. Two towns sharing a name in one
-- region would be a gazetteer problem, not something to model around.
create unique index place_identity_idx
  on public.place (country_code, name, coalesce(region, ''));
create index place_country_idx on public.place (country_code);

grant select on public.place to authenticated, anon;
alter table public.place enable row level security;

-- A gazetteer is public reference data. An auditor picking where they work and
-- a charity booking an audit both need to read it, and it says nothing about
-- anybody.
create policy place_readable on public.place
  for select to authenticated using (true);

-- ---------------------------------------------------------------------------
-- Where an audit happens.
--
-- The postcode CHECK goes. An address is free text in whatever shape the
-- country writes it, and `place_id` is what matching uses.
-- ---------------------------------------------------------------------------
alter table public.audit drop constraint if exists postcode_format;

alter table public.audit
  add column place_id uuid references public.place (id) on delete restrict;

create index audit_place_idx on public.audit (place_id, status);

comment on column public.audit.place_id is
  'Resolved when the audit is booked. What auditor matching joins on.';
comment on column public.audit.postcode is
  'The address as written, in whatever shape the country uses. Display and '
  'navigation only — never matching, and no longer format-checked.';

-- ---------------------------------------------------------------------------
-- What an auditor told us about travelling.
-- ---------------------------------------------------------------------------
alter table public.auditor_profile
  add column base_place_id       uuid references public.place (id) on delete restrict,
  add column max_travel_minutes  integer,
  add column travel_mode         public.travel_mode;

alter table public.auditor_profile
  add constraint travel_minutes_sane
  check (max_travel_minutes is null or max_travel_minutes between 5 and 240);

comment on column public.auditor_profile.max_travel_minutes is
  'As the auditor gave it. The straight-line radius is derived from this and '
  'the mode, never stored in its place — so better journey times can replace '
  'the estimate without asking anyone again.';

-- ---------------------------------------------------------------------------
-- Which places an auditor covers.
--
-- `source` keeps the circle and the corrections apart. A place the auditor
-- unticked is an `excluded` row rather than a missing one, so re-running the
-- derivation after they move house does not quietly undo their correction.
-- ---------------------------------------------------------------------------
create type public.coverage_source as enum ('derived', 'added', 'excluded');

alter table public.auditor_coverage
  add column place_id uuid references public.place (id) on delete restrict,
  add column source   public.coverage_source not null default 'derived';

-- postcode_area becomes nullable while both models coexist through the
-- backfill; the next migration drops it once nothing reads it.
alter table public.auditor_coverage alter column postcode_area drop not null;
alter table public.auditor_coverage drop constraint if exists postcode_area_format;

create unique index auditor_coverage_place_idx
  on public.auditor_coverage (auditor_id, place_id)
  where place_id is not null;

create index auditor_coverage_matching_idx
  on public.auditor_coverage (place_id)
  where source <> 'excluded';
