#!/usr/bin/env bash
# Writes the local .env files from the running Supabase stack.
#
# The keys are local-only defaults that change whenever the stack is recreated,
# so they are generated rather than copied by hand. All three files are
# gitignored. Run `pnpm db:start` first.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! ENV_OUT=$(cd packages/db && supabase status -o env 2>/dev/null); then
  echo "Supabase is not running. Start it with: pnpm db:start" >&2
  exit 1
fi

# `|| true` matters: with `set -e` and `pipefail`, a grep that matches nothing
# kills the script before it can say why. Key names have also moved between
# CLI versions, so try both spellings.
get() {
  for key in "$@"; do
    value=$(printf '%s\n' "$ENV_OUT" | grep -m1 "^${key}=" | cut -d= -f2- | tr -d '"') || true
    if [ -n "${value:-}" ]; then printf '%s' "$value"; return 0; fi
  done
  return 0
}

URL="http://127.0.0.1:54321"
ANON=$(get ANON_KEY SUPABASE_ANON_KEY PUBLISHABLE_KEY)
SERVICE=$(get SERVICE_ROLE_KEY SUPABASE_SERVICE_ROLE_KEY SECRET_KEY)

if [ -z "${ANON:-}" ]; then
  echo "Could not find an anon key in \`supabase status -o env\`. It reported:" >&2
  printf '%s\n' "$ENV_OUT" | cut -d= -f1 | sed 's/^/  /' >&2
  exit 1
fi

cat > .env <<INNER
# Generated by scripts/local-env.sh. Gitignored. Do not commit.
PICKSEL_ENV=local

NEXT_PUBLIC_SUPABASE_URL=$URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON
SUPABASE_SERVICE_ROLE_KEY=$SERVICE

EXPO_PUBLIC_SUPABASE_URL=$URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$ANON
INNER

cat > apps/portal/.env.local <<INNER
# Generated by scripts/local-env.sh. Gitignored. Do not commit.
NEXT_PUBLIC_SUPABASE_URL=$URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON
SUPABASE_SERVICE_ROLE_KEY=$SERVICE
INNER

cat > apps/field/.env <<INNER
# Generated by scripts/local-env.sh. Gitignored. Do not commit.
# 127.0.0.1 reaches the host only from a simulator. On a physical device use
# your machine's LAN address, e.g. http://192.168.1.20:54321
EXPO_PUBLIC_SUPABASE_URL=$URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$ANON
INNER

echo "Wrote .env, apps/portal/.env.local, apps/field/.env"
