#!/usr/bin/env bash
# Writes the local .env files from the running Supabase stack.
#
# The keys are local-only defaults that change whenever the stack is recreated,
# so they are generated rather than copied by hand. All three files are
# gitignored. Run `pnpm db:start` first.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! ENV_OUT=$(cd packages/db && supabase status -o env 2>/dev/null); then
  echo "Supabase is not running. Start it with: pnpm db:start" >&2
  exit 1
fi

get() { printf '%s\n' "$ENV_OUT" | grep "^$1=" | cut -d= -f2- | tr -d '"'; }

URL="http://127.0.0.1:54321"
ANON=$(get ANON_KEY)
SERVICE=$(get SERVICE_ROLE_KEY)

[ -n "$ANON" ] || { echo "Could not read ANON_KEY from supabase status" >&2; exit 1; }

cat > .env <<INNER
# Generated by scripts/local-env.sh. Gitignored. Do not commit.
PICKSEL_ENV=local

NEXT_PUBLIC_SUPABASE_URL=$URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON
SUPABASE_SERVICE_ROLE_KEY=$SERVICE

EXPO_PUBLIC_SUPABASE_URL=$URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$ANON
INNER

cat > apps/portal/.env.local <<INNER
# Generated by scripts/local-env.sh. Gitignored. Do not commit.
NEXT_PUBLIC_SUPABASE_URL=$URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON
SUPABASE_SERVICE_ROLE_KEY=$SERVICE
INNER

cat > apps/field/.env <<INNER
# Generated by scripts/local-env.sh. Gitignored. Do not commit.
# 127.0.0.1 reaches the host only from a simulator. On a physical device use
# your machine's LAN address, e.g. http://192.168.1.20:54321
EXPO_PUBLIC_SUPABASE_URL=$URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$ANON
INNER

echo "Wrote .env, apps/portal/.env.local, apps/field/.env"
